### ISSUE TITLE
I tried this code but it does not work for me? 

### ISSUE THREAD

**Issue by GEEKS0007** [xFrieDSpuDx/SMS-Bulk-Sender#1]
Hi there , 
i downloaded your code and tried to use it but it does not worked for me

**Comment by xFrieDSpuDx** [comment]
Please can you provide some more details for exactly what didn't work and what you did? Did the application provide any error messages?

I just tried downloading the project and running it as a file on my desktop and it worked as expected.

**Comment by GEEKS0007** [comment]
let me attach a screenshot.

**Comment by GEEKS0007** [comment]
![image](https://user-images.githubusercontent.com/54582941/159471449-1c28de55-1b1b-4ca4-9dc2-918b54e30a7f.png)

**Comment by xFrieDSpuDx** [comment]
Thank you. I think I know the issue now. 

I had only tested it on a UK number.

I will get an update pushed by 11pm GMT.

**Comment by GEEKS0007** [comment]
Ok Sure. i ll be waiting.

**Comment by xFrieDSpuDx** [comment]
Thanks for the images and description of the error. I have pushed changes that should fix the issue.

It is currently limited to being able to send numbers from the same international country code as the Telnyx number.

Please can you confirm if this fix works, then I will close the issue.

**Comment by GEEKS0007** [comment]
Ok let me check and I ll revert you the status here.

Sent from my iPhone

On 23-Mar-2022, at 4:33 AM, xFrieDSpuDx ***@***.***> wrote:

﻿

Thanks for the images and description of the error. I have pushed changes that should fix the issue.

It is currently limited to being able to send numbers from the same international country code as the Telnyx number.
