### ISSUE TITLE
Errors when adding number from my country

### ISSUE THREAD

**Issue by uchenna2k2** [xFrieDSpuDx/SMS-Bulk-Sender#5]
I have noticed that I get errors with my country number, Nigeria. The format is +23480XXXXXXXX but it adds 1 in front just like this +123480XXXXXXXX throwing up errors. How do I fixed this?

**Comment by xFrieDSpuDx** [comment]
Thank you for bringing this up.

At the moment the application only has the ability to send to numbers that have the same country code as the Telnyx send number. 
This was done for two main reasons:

- Ease of development as I don't have access to a lot of foreign mobile numbers
- Easy of checking numbers for errors, I didn't have to write a huge amount of error checking

I do have it in the plan to update this shortcoming, but I have no deadline scheduled just yet.

**Comment by xFrieDSpuDx** [comment]
I have made a small update that allows messages to be sent to any number.

The error checking for number length is still very rudimentary, I will take a look at implementing something more thorough in the future.

Any questions or problems give me a shout.

**Comment by uchenna2k2** [comment]
Thanks
