### ISSUE TITLE
Do you have phone numbers validator

### ISSUE THREAD

**Issue by uchenna2k2** [xFrieDSpuDx/SMS-Bulk-Sender#6]
I am looking for a good phone number validator, I don't know if you have such so I can use it to validate my phone numbers. Thanks

**Comment by xFrieDSpuDx** [comment]
I don't currently. This has just been a small side project to let me bulk send SMS messages for some volunteering I do and all my numbers are to the same country so just the most basic checks were enough for me.

However as there has been interest in this project I will eventually be including [Googles library for parsing and validating numbers ](https://github.com/google/libphonenumber) into it.

If you check out the link above to their Git repo they have a number of demos for different languages [here is the JavaScript one](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)

Kind regards,

**Comment by uchenna2k2** [comment]
Thanks for getting back to me

**Comment by uchenna2k2** [comment]
I will appreciate if you work on the script and add more features please

**Comment by xFrieDSpuDx** [comment]
Googles phone number validation and parsing library libphonenumber has been included and is now used to validate numbers.
